name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  tag:
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: write
    uses: ./.github/workflows/tag.yml

  publish:
    needs: [test, tag]
    if: always() && needs.test.result == 'success' && (github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch') && (needs.tag.result == 'success' || needs.tag.result == 'skipped')
    uses: ./.github/workflows/publish.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
